apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api-PROJETO
  namespace: $K8S_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-PROJETO
  template:
    metadata:
      labels:
        app: api-PROJETO
    spec:
      containers:
        - image: $IMAGE
          imagePullPolicy: IfNotPresent
          name: api-PROJETO
          env:
            - name: APPLICATION_DOMAIN
              value: $APPLICATION_DOMAIN
            - name: PORT_SERVER
              value: $PORT_SERVER
            - name: NODE_ENV
              value: $NODE_ENV
            - name: URL_DOCUMENTACAO
              value: $URL_DOCUMENTACAO
            - name: DB_NAME
              value: $DB_NAME
            - name: DB_PASS
              value: $DB_PASS
            - name: DB_HOST
              value: DB_HOST
          resources: {}
          ports:
            - name: http
              containerPort: $PORT_SERVER
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets: 
        - name: registry