apiVersion: v1
kind: Service
metadata:
  name: service-api-PROJETO
  namespace: $K8S_NAMESPACE
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: api-PROJETO
  ports:
    - name: http
      port: $PORT_SERVER
      protocol: TCP
